### ISSUE TITLE
안녕 건웅아

### ISSUE THREAD

**Issue by YuEunsol** [ddugel3/ddugel3#1]
만나서 ㅁ반가원~!~!~!!!!!!!!!!!!!!!!!!!!!~!~!~~~~~
┬┴┬┴┤ ͜ʖ ͡°) ├┬┴┬┴
┬┴┬┴┤ ͜ʖ ͡°) ├┬┴┬┴
┬┴┬┴┤ ͜ʖ ͡°) ├┬┴┬┴                  훔쳐보러 왔어~~~~~~~
┬┴┬┴┤ ͜ʖ ͡°) ├┬┴┬┴   
┬┴┬┴┤ ͜ʖ ͡°) ├┬┴┬┴

                     내     꺼          두         ̿̿ ̿̿ ̿̿ ̿'̿'\\з= ( ▀ ͜͞ʖ▀) =ε//’̿’̿ ̿ ̿̿ ̿̿ ̿̿
                                  훔  쳐       보                   러          ̿̿ ̿̿ ̿̿ ̿'̿'\\з= ( ▀ ͜͞ʖ▀) =ε//’̿’̿ ̿ ̿̿ ̿̿ ̿̿
                                                 와    아          아                 아                         앙         ̿̿ ̿̿ ̿̿ ̿'̿'\\з= ( ▀ ͜͞ʖ▀) =ε//’̿’̿ ̿ ̿̿ ̿̿ ̿̿

**Comment by ddugel3** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
